---

- jenkins_job:
    config: "{{ lookup('file', 'files/test.xml') }}"
    name: "{{ job_name }}"
    password : "{{jenkins_password}}"
    url: http://{{jenkins_url}}:{{jenkins_port}}
    user: "{{ jenkins_user }}"